services:
  - name: "Websites"
    api:
      - url: "https://www.chinahighlights.com/"
      - url: "https://www.globalhighlights.com/"
      - url: "https://www.japanhighlights.com/"
      - url: "https://www.highlightstravel.com/"
  - name: "Servers"
    health:
      - url: "https://p9axztuwd7x8a7.mycht.cn/whatsapp_server/wa_server_test"
      - url: "https://p9axztuwd7x8a7.mycht.cn/mail-server/service-mail/service_mail_test"
    api:
      - url: "https://wai-01-qq4qmtq7wc9he4.chinahighlights.cn/api/v1/channels/sessions"
      - url: "https://wai-02-qq4qmtq7wc9he4.chinahighlights.cn/api/v1/channels/sessions"
      - url: "https://wai-03-u2xlvlxf6jhm42.chinahighlights.cn/api/v1/channels/sessions"
      - url: "https://wai-04-qnwgv2vpfp7o4.chinahighlights.cn/api/v1/channels/sessions"
