name: Auto Deploy Report

on:
  schedule:
    - cron: '*/60 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "🔄 Checkout code"
        uses: actions/checkout@v4

      - name: "🐹 Set up Go"
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: "🏗️ Build and run PongHub"
        run: |
          mkdir -p bin data
          git clone --branch gh-pages https://github.com/${{ github.repository }}.git || true
          if [ -f ponghub/ponghub_log.json ]; then
            cp ponghub/ponghub_log.json data/ponghub_log.json
          else
            echo "New installation, no previous data found."
          fi
          make run || true

      - name: "📦 Prepare publish directory"
        run: |
          mkdir -p publish/static
          cp -r data/* publish/
          cp -r static/* publish/static/
          if [ -f CNAME ]; then
            cp CNAME publish/
          else
            echo "No CNAME file found."
          fi
          touch publish/.nojekyll

      - name: "🚀 Deploy to GitHub Pages"
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: publish
          git-config-name: github-pages-deploy-action
          git-config-email: noreply@github.com

      - name: "⚠️ Notify Unavailable Services"
        run: |
          if [ -f data/notify.txt ] && [ -s data/notify.txt ]; then
            echo "Unavailable services found:"
            cat data/notify.txt
            exit 1
          else
            echo "No unavailable services."
          fi
